baseURL = "https://tmadanymamlouk.github.io/theinnovationengineer-blog/"
languageCode = "de-de"
title = "TheInnovationEngineer Blog"
theme = "PaperMod"

[params]
  homeInfoParams = { title = "Willkommen beim Innovation Engineer Blog", content = "Gedanken zu KI, Software und Zukunftstechnologien." }
  ShowReadingTime = true
  ShowShareButtons = true
  defaultTheme = "auto"

[outputs]
  home = ["HTML", "RSS", "JSON"]
