baseURL = "https://tmadanymamlouk.github.io/theinnovationengineer-blog/"
languageCode = "de-de"
title = "TheInnovationEngineer Blog"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  defaultTheme = "auto"

[outputs]
  home = ["HTML", "RSS", "JSON"]
