name: Build and Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # oder master, je nachdem wie dein Branch heißt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (mit Submodulen)
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.8'

      - name: Build website
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
